# Usa uma imagem oficial do Node leve
FROM node:20-alpine

# Define a pasta de trabalho
WORKDIR /app

# Copia os arquivos de configuração do Node
COPY package.json package-lock.json* ./

# Instala as dependências
RUN npm install

# Copia o resto do código do frontend
COPY . .

# Expõe a porta padrão do Vite
EXPOSE 5173

# Comando para rodar o frontend no modo de desenvolvimento
CMD ["npm", "run", "dev", "--", "--host"]