# Usa uma imagem oficial do Python leve
FROM python:3.12-slim

# Define a pasta de trabalho dentro do container
WORKDIR /app

# Instala as dependências do sistema
RUN apt-get update && apt-get install -y gcc libpq-dev

# Copia tudo da sua pasta atual para dentro do container
COPY . /app/

# Instala as bibliotecas do Python
RUN pip install --no-cache-dir django djangorestframework djangorestframework-simplejwt djangorestframework-simplejwt django-cors-headers

# Expõe a porta que o Django vai rodar
EXPOSE 8000

# Comando para rodar o servidor
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]