# Generated by Django 6.0.3 on 2026-03-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='atividades_arquivos/'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='respostas_arquivos/'),
        ),
    ]
